language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libasound2-dev
      - libudev-dev
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true