name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        lfs: true
        submodules: true
    - name: Install packages
      run: sudo apt-get install libasound2-dev libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
