name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
      with:
        lfs: true
        submodules: true
    - name: Cache apt packages
      uses: actions/cache@v1
      with:
        path: /var/cache/apt/archives
        key: apt-packages
    - name: Update package list
      run: sudo apt-get update
    - name: Install packages
      run: sudo apt-get install libasound2-dev libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
